const chatWindow = document.getElementById('chatWindow');
const questionInput = document.getElementById('questionInput');
const sendButton = document.getElementById('sendButton');

function scrollToBottom() { chatWindow.scrollTop = chatWindow.scrollHeight; }
function renderUserMessage(text) { const node = document.createElement('div'); node.className = 'chat-message user-message'; node.innerHTML = `<div class="message-avatar" style="background:#dbeafe;color:#2563eb"><i class="bi bi-person"></i></div><div class="message-body"><div class="message-meta">You <span>Just now</span></div><p>${escapeHtml(text)}</p></div>`; chatWindow.appendChild(node); scrollToBottom(); }
function renderAssistantMessage(data) { const node = document.createElement('div'); node.className = 'chat-message assistant-message'; node.innerHTML = `<div class="message-avatar"><i class="bi bi-stars"></i></div><div class="message-body"><div class="message-meta">Accounting Assistant <span>Just now</span></div><p>${formatMarkdown(data.answer)}</p><button class="copy-answer" title="Copy answer"><i class="bi bi-copy"></i> Copy answer</button></div>`; node.querySelector('.copy-answer').addEventListener('click', () => navigator.clipboard.writeText(data.answer)); chatWindow.appendChild(node); renderSources(data.sources); document.getElementById('confidenceValue').textContent = `${data.confidence}%`; document.getElementById('confidenceBar').style.width = `${data.confidence}%`; scrollToBottom(); }
function showTypingIndicator() { const node = document.createElement('div'); node.id = 'typingIndicator'; node.className = 'chat-message assistant-message'; node.innerHTML = '<div class="message-avatar"><i class="bi bi-stars"></i></div><div class="message-body"><div class="message-meta">Accounting Assistant <span>Working...</span></div><p class="typing-dots"><i></i><i></i><i></i></p></div>'; chatWindow.appendChild(node); scrollToBottom(); }
function renderSources(sources = []) { const list = document.getElementById('sourcesList'); list.innerHTML = sources.map(source => `<div class="source-item"><i class="bi bi-file-earmark-text"></i><span>${escapeHtml(source)}</span></div>`).join('') || '<div class="empty-source">No source references returned.</div>'; }
function escapeHtml(text) { const element = document.createElement('div'); element.textContent = text; return element.innerHTML; }
function formatMarkdown(text) { return escapeHtml(text).replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br>'); }
async function handleQuestion() { const question = questionInput.value.trim(); if (!question || sendButton.disabled) return; renderUserMessage(question); questionInput.value = ''; questionInput.style.height = 'auto'; sendButton.disabled = true; showTypingIndicator(); try { const data = await sendQuestion(question); document.getElementById('typingIndicator')?.remove(); renderAssistantMessage(data); loadHistory().then(renderHistory); } catch (error) { document.getElementById('typingIndicator')?.remove(); renderAssistantMessage({answer: 'I could not reach the accounting service. Please check that the API is running and try again.', sources: [], confidence: 0}); console.error(error); } finally { sendButton.disabled = false; questionInput.focus(); } }
sendButton.addEventListener('click', handleQuestion); questionInput.addEventListener('keydown', event => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); handleQuestion(); } }); questionInput.addEventListener('input', () => { questionInput.style.height = 'auto'; questionInput.style.height = `${Math.min(questionInput.scrollHeight, 80)}px`; }); document.querySelectorAll('.suggestion').forEach(button => button.addEventListener('click', () => { questionInput.value = button.dataset.question; handleQuestion(); }));
